AttendanceApp_MVC/AttendanceApp_MVC/ViewModels/AttendanceViewModel.cs
using AttendanceBook.Models;

namespace AttendanceBookWeb.ViewModels
{
    public class AttendanceViewModel
    {
        public Attendance Attendance { get; set; }
        //public string ImageUrl { get; set; }
    }
}

AttendanceApp_MVC/AttendanceApp_MVC/Controllers/AttendancesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AttendanceBook.DataAccess.Data;
using AttendanceBook.Models;
using AttendanceBookWeb.ViewModels;
using Microsoft.AspNetCore.Http;

namespace AttendanceBookWeb.Controllers
{
    public class AttendancesController : Controller
    {
        private readonly AttendanceBookAppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AttendancesController(AttendanceBookAppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Attendances
        public async Task<IActionResult> Index(string? fullName = null)
        {

            var attendance = new List<Attendance>();


            if (string.IsNullOrWhiteSpace(fullName))
            {
                attendance = await _context.Attendances.ToListAsync();
                return View(attendance);

            }
            attendance = await _context.Attendances
                .Where(a => EF.Functions.Like(a.FullName, $"%{fullName}%")).ToListAsync();
            if (attendance == null)
            {
                return RedirectToAction("Index");
            }
            return View(attendance);




        }

        // GET: Attendances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendance = await _context.Attendances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }

            return View(attendance);
        }

        // GET: Attendances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Attendances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FullName,Age,AttendanceReason")] AttendanceRequest request)
        {
            if (ModelState.IsValid)
            {
               
                var attendanceData = new Attendance
                {
                    FullName = request.FullName,
                    Age = request.Age,
                    AttendanceReason = request.AttendanceReason,
                    CheckIn = DateTime.Now,
                    IsCheckOut = false
                };

               attendanceData = _context.Attendances.Add(attendanceData).Entity;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View(request);
        }

        // GET: Attendances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendance = await _context.Attendances.FindAsync(id);
            if (attendance == null)
            {
                return NotFound();
            }
            return View(attendance);
        }

        // POST: Attendances/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Age,CheckInTime,CheckOutTime,AttendanceReason")] Attendance attendance)
        {
            if (id != attendance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attendance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttendanceExists(attendance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(attendance);
        }

        // GET: Attendances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendance = await _context.Attendances
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attendance == null)
            {
                return NotFound();
            }

            return View(attendance);
        }

        // POST: Attendances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var attendance = await _context.Attendances.FindAsync(id);
            if (attendance != null)
            {
                _context.Attendances.Remove(attendance);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttendanceExists(int id)
        {
            return _context.Attendances.Any(e => e.Id == id);
        }

        public async Task<IActionResult> CheckOut(int attendanceId)
        {
            var attendance = await _context.Attendances.FirstOrDefaultAsync(a => a.Id == attendanceId);
            if(attendance == null)
            {
                return RedirectToAction("Index");
            }
            attendance.CheckOut = DateTime.Now;
            attendance.IsCheckOut = true;
            _context.Attendances.Update(attendance);
           await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }


        //public IActionResult InsertImage(AttendanceViewModel attendanceVM, IFormFile? file)
        //{
        //    string wwwRootPath = _webHostEnvironment.WebRootPath;
        //    if (file != null) 
        //    { 
        //        string fileName = Guid.NewGuid().ToString().ToString() + Path.GetExtension(file.FileName);
        //        string imagePath = Path.Combine(wwwRootPath, fileName);
        //        if (!string.IsNullOrEmpty(attendanceVM.Attendance.ImageUrl))
        //        {
        //            var oldImagePath = Path.Combine(wwwRootPath, attendanceVM.Attendance.ImageUrl.TrimStart('\\'));
        //            if (System.IO.File.Exists(oldImagePath))
        //            {
        //                System.IO.File.Delete(oldImagePath);
        //            }
        //        }

        //        using (var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create))
        //        {
        //            file.CopyTo(fileStream);
        //        }
        //        attendanceVM.Attendance.ImageUrl = @"\images\imagecapture" + file;

        //        return View(attendanceVM);
        //    }
        //    return RedirectToAction($"{nameof(Index)}");
        //}
    }
}

AttendanceApp_MVC/AttendanceApp_MVC/Views/Attendances/Create.cshtml
@model AttendanceBook.Models.Attendance

@{
    ViewData["Title"] = "Create";
}

<style>

    .info-section{
        display: flex;
        gap: 20px;
        justify-content: center;
        margin: 20px;
    }

    .submit-action{
        justify-content: center;
        display: flex;
        margin-top: 60px;
    }



    @@media (max-width: 991px){
        .info-section{
            flex-direction: column;
        }
    }


</style>


<h4 style="justify-content: center; display: flex;">
    Create Attendance
</h4>
<hr />
<div class="row" >
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-12  info-section">
                <div class="form-group col-lg-5 col-sm-12">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>




                <div class="form-group col-lg-5 col-sm-12">
                    <label asp-for="Age" class="control-label"></label>
                    <input asp-for="Age" class="form-control" />
                    <span asp-validation-for="Age" class="text-danger"></span>
                </div>

        </div>


        <div class="col-12  info-section">
            <div class="col-lg-5 col-sm-12 form-group">
                <label asp-for="AttendanceReason" class="control-label"></label>
                <input asp-for="AttendanceReason" class="form-control" />
                <span asp-validation-for="AttendanceReason" class="text-danger"></span>
            </div>

            <div class="col-5 "></div>
            </div>



            
            <div class="form-group submit-action">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
</div>

<div style="margin: 80px;">
    <a  asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AttendanceApp_MVC/AttendanceApp_MVC/Views/Attendances/Delete.cshtml
@model AttendanceBook.Models.Attendance

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendance</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckIn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CheckOut)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AttendanceReason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AttendanceReason)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AttendanceApp_MVC/AttendanceApp_MVC/Views/Attendances/Details.cshtml
@model AttendanceBook.Models.Attendance

@{
    ViewData["Title"] = "Details";
}

<style>
    .details-info{
        display: flex;
        justify-content: center;
        align-items: center;
        margin:20px;
        flex-direction:column;
        font-family: "Montserrat";
    }

    .card-details{
        margin: 20px;
        /* min-height: 250px; */
        border: 1px solid beige;
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 30px;
    }

    .details-name{
        display: flex;
        justify-content: center;

    }
    .check-info{
        margin: 20px;
    }

    .checkout-btn{
        display: flex;
        justify-content: center;
        padding: 10px;
    }

    
    .blue-bold-font{
        color: #202068;
        font-weight: bold;
    }


</style>

<div>
    <h4>Attendance Details</h4>
    <hr />
    <div class="details-info">


        <div class="details-name">
            <h6 class="blue-bold-font">@Model.FullName</h6>
        </div>
        <div class="row col-10 card-details">


            <div class="col-sm-5 check-info">
                <p> <strong>Age : </strong> <span class="blue-bold-font">@Model.Age</span></p>
            </div>

            <div class="col-sm-5 check-info">
                <p><strong>Attendance Reason : </strong><span class="blue-bold-font">@Model.AttendanceReason</span></p>
            </div>

             <div class="col-sm-5">
                <p> <strong>Check In : </strong><span class="blue-bold-font">@Model.CheckIn.ToString("dddd, MMMM dd, yyyy HH:mm:ss")</span></p>
                </div>
           
                <div class="col-sm-5">
                <p><strong>CheckOut : </strong><span class="blue-bold-font">@(Model.CheckOut.HasValue? Model.CheckOut.Value.ToString("dddd, MMMM dd, yyyy HH:mm:ss"): "N/A")</span></p>
               </div>

  
            @if(Model.IsCheckOut == false)
            {
                <div class="checkout-btn">
                    <button type="button"
                            class="btn btn-dark "
                            onclick="location.href='@Url.Action("CheckOut", "Attendances", new { attendanceId = Model.Id})'">
                        Check Out
                    </button>
                </div>

            }
           

        </div>
    </div>
   
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AttendanceApp_MVC/AttendanceApp_MVC/Views/Attendances/Edit.cshtml
@model AttendanceBook.Models.Attendance

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Attendance</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttendanceReason" class="control-label"></label>
                <input asp-for="AttendanceReason" class="form-control" />
                <span asp-validation-for="AttendanceReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AttendanceApp_MVC/AttendanceApp_MVC/Views/Attendances/Index.cshtml
@model IEnumerable<AttendanceBook.Models.Attendance>

@{
    ViewData["Title"] = "Index";
}

<h4 style="justify-content: center; display: flex;"> 
    Attendance Records
</h4>
<hr />
<p style="margin-left:10px; margin-bottom:5px;" >
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Attendances" asp-action="Index" method="get">
    <div class="col-6" style="align-content: baseline;gap:10px; display: flex; padding: 10px">
        <input type="text" name="fullName" class="form-control" />
        <input class="btn btn-dark " type="submit" value="Search" />

        <div >
            @* <button type="button"
                class="btn btn-dark "
                onclick="location.href='@Url.Action("Search", "Attendances")'">
            Search
        </button> *@
        </div>
    </div>
   
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CheckOut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttendanceReason)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AttendanceReason)
            </td>
            <td>
                @if (!item.IsCheckOut)
                    {

                        <span> <a asp-action="CheckOut" asp-route-attendanceId="@item.Id">Check Out</a> |  </span>
                              
    
                }
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            
            </td>
        </tr>
}
    </tbody>
</table>